# Conda environment for BacterialSlimulator
name: bactslim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - msprime=0.7.4
  - numpy=1.16.4
  - pandas=0.25.1
  - scikit-allel=1.2.1
# Additional pip dependencies
  - pip:
      - pyslim

