# Conda environment for BacterialSlimulator
name: bactslim
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.7
  - msprime=0.7.4
  - numpy=1.16.4
  - pandas=0.25.1
  - scikit-allel=1.2.1
  - slim=3.4
  - pyslim=0.401
  - ms=2014_03_04
